# nixpacks.toml

providers = ["python", "node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.setup]
# Memastikan pip dan gcc terinstal secara eksplisit di awal
nixPkgs = ["python3", "python3Packages.pip", "gcc"]

[phases.build]
cmds = [
    "npm --prefix client install",
    "npm --prefix client run build",
    "pip3 install -r server/requirements.txt --break-system-packages"
]

[start]
cmd = "gunicorn --chdir server app:app"