# nixpacks.toml

[phases.setup]
# Perintah ini memaksa Railway menggunakan arsip paket yang lebih baru
# di mana Node.js v20 tersedia dan menjadi default.
nixpkgsArchive = 'bf744fe90419885eefced41b3e5ae442d732712d'

[phases.build]
# Perintah build Anda tetap sama
cmds = [
    "npm --prefix client install",
    "npm --prefix client run build",
    "pip install -r server/requirements.txt"
]

[start]
# Perintah start Anda tetap sama
cmd = "gunicorn --chdir server app:app"