# nixpacks.toml

providers = ["python", "node"]

[variables]
NIXPACKS_NODE_VERSION = "20"

[phases.build]
# Perintah build Anda tetap sama
cmds = [
    "npm --prefix client install",
    "npm --prefix client run build",
    "pip3 install -r server/requirements.txt"
]

[start]
# Perintah start Anda tetap sama
cmd = "gunicorn --chdir server app:app"